/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    CardGrid: typeof import('./src/components/CardGrid.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    EditModal: typeof import('./src/components/EditModal/EditModal.vue')['default']
    EnvironmentBadge: typeof import('./src/components/EnvironmentBadge.vue')['default']
    FormData: typeof import('./src/components/EditModal/FormData.vue')['default']
    IconPreview: typeof import('./src/components/EditModal/IconPreview.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
